name = "image-gen-mcp"
main = "src/worker.ts"
compatibility_date = "2026-05-20"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "IMAGES"
id = "8bb79983ec9b468eae52ceaa27ba3cae"
